---

- hosts: all
  become: true
  tasks:
  
  - name: Install Apache HTTP and PHP
    dnf:
      name:
        - php-cli
        - php-common
        - "{{ apache_package }}"
        - "{{ php_package }}"  
      state: present
      update_cache: yes
