---

- hosts: all
  become: true
  tasks:
  
  - name: Update Repository Index
    dnf:
      update_cache: yes

  - name: Install Apache HTTP Server
    dnf:
      name: httpd
      state: present

  - name: Add PHP Support for Apache
    dnf:
      name:
        - php
        - php-cli
        - php-common
      state: present
