---

- hosts: all
  become: true
  tasks:

  - name: Install Updates
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Rocky"

- hosts: web_servers
  become: true
  tasks:
 
  - name: Install Apache HTTP and PHP
    tags: apache,rocky,httpd
    dnf:
      name:
        - php-cli
        - php-common
        - "{{ apache_package }}"
        - "{{ php_package }}"  
      state: present
  
  - name: Start httpd (Rocky)
    tags: apache,rocky,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "Rocky"    

  - name: Copy Default HTML File
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: Install MariaDB
    tags: rocky,db,mariadb
    dnf:
      name: 
        - mariadb
        - mariadb-server
      state: latest
    when: ansible_distribution == "Rocky"

- hosts: file_servers
  become: true
  tasks:
    
  - name: Install Samba
    tags: samba
    package:
      name: samba
      state: latest

- hosts: workstations
  become: true
  tasks:

    # - name: Install unzip
    # package:
    # name: unzip

    # - name: Install terraform
    # unarchive:
    #   src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
    #   dest: /usr/local/bin
    #   remote_src: yes
    #   mode: 0755
    # owner: root
    # group: root
